-- # Tennessee's Opioid Crisis

-- Opioids are a class of drugs including prescription pain relievers such as oxycodone and hydrocodone, the synthetic opioid fentanyl, and the illegal drug heroin. These drugs produce euphoria in addition to pain relief, which can lead to dependence, addiction, overdose, and death. 

-- In the late 1990s, opioids began to be prescribed at high rates, which led to widespread misuse and ultimately created a serious national health crisis. In 2019, more than 130 people per day died from opioid-related drug overdoses in the United States. Tennessee has been one of the hardest-hit states in the opioid epidemic, with more than 1300 overdose deaths in 2018.

-- In this project, you will be working with a database created from the 2017 Medicare Part D Prescriber Public Use File to answer the following questions:  
-- * Which Tennessee counties had a disproportionately high number of opioid prescriptions?
-- * Who are the top opioid prescibers for the state of Tennessee?
-- * What did the trend in overdose deaths due to opioids look like in Tennessee from 2015 to 2018?
-- * Is there an association between rates of opioid prescriptions and overdose deaths by county?
-- * Is there any association between a particular type of opioid and number of overdose deaths?

-- Note that some zip codes will be associated with multiple fipscounty values in the zip_fips table. To resolve this, use the fipscounty with the highest tot_ratio for each zipcode.

-- Feel free to include any additional data sets, but it is not a requirement.

-- With your group, create a 10 minute presentation addressing these questions.

-- Question 1: Which Tennessee counties had a disproportionately high number of opioid prescriptions?
-- WITH max_zips AS (
-- 	SELECT DISTINCT zip
-- 		, MAX(tot_ratio) as max_ratio
-- 	FROM zip_fips
-- 	GROUP BY zip
-- )
-- , sort_fips AS (	
-- 	SELECT zip_fips.zip
-- 		, zip_fips.fipscounty
-- 		, zip_fips.tot_ratio
-- 	FROM zip_fips
-- 		INNER JOIN max_zips
-- 			ON zip_fips.zip = max_zips.zip
-- 			AND zip_fips.tot_ratio = max_zips.max_ratio
-- )
-- , total_claims AS (
-- 	SELECT fips_county.county
-- 		, SUM(prescription.total_claim_count) AS total_claims
-- 	FROM fips_county
-- 		INNER JOIN population
-- 			USING(fipscounty)
-- 		INNER JOIN sort_fips
-- 			USING (fipscounty)
-- 		INNER JOIN prescriber
-- 			ON sort_fips.zip = prescriber.nppes_provider_zip5
-- 		INNER JOIN prescription
-- 			USING (npi)
-- 		INNER JOIN drug
-- 			USING (drug_name)
-- 	WHERE fips_county.state ILIKE 'TN'
-- 	GROUP BY fips_county.county
-- )
-- SELECT fips_county.county
-- 	, population.population
-- 	, SUM(prescription.total_claim_count) AS total_opioids
-- 	, (SUM(prescription.total_claim_count)/total_claims.total_claims)*100 AS opioid_pct
-- 	, RANK() OVER(ORDER BY SUM(prescription.total_claim_count) DESC) AS opioids_rank
-- FROM fips_county
-- 	INNER JOIN population
-- 		USING (fipscounty)
-- 	INNER JOIN sort_fips
-- 		USING (fipscounty)
-- 	INNER JOIN prescriber
-- 		ON sort_fips.zip = prescriber.nppes_provider_zip5
-- 	INNER JOIN prescription
-- 		USING (npi)
-- 	INNER JOIN drug
-- 		USING (drug_name)
-- 	INNER JOIN total_claims
-- 		USING (county)
-- WHERE drug.opioid_drug_flag ILIKE 'Y'
-- 	AND fips_county.state ILIKE 'TN'
-- GROUP BY fips_county.county
-- 	, population.population
-- 	, total_claims.total_claims
-- ORDER BY opioid_pct DESC

-- --Question 2: Who are the top opioid prescibers for the state of Tennessee?
-- SELECT prescriber.npi
-- 	, CONCAT(prescriber.nppes_provider_first_name,' ',prescriber.nppes_provider_last_org_name) as full_name
-- 	, SUM(prescription.total_claim_count) AS total_opioids
-- FROM prescriber
-- 	INNER JOIN prescription
-- 		USING(npi)
-- 	INNER JOIN drug
-- 		USING(drug_name)
-- WHERE drug.opioid_drug_flag ILIKE 'Y'
-- 	AND prescriber.nppes_provider_state ILIKE 'TN'
-- GROUP BY prescriber.npi
-- 	, prescriber.nppes_provider_first_name
-- 	, prescriber.nppes_provider_last_org_name
-- ORDER BY total_opioids DESC;

-- Question 3: What did the trend in overdose deaths due to opioids look like in Tennessee from 2015 to 2018?
-- WITH overdose_fixed AS (
-- 	SELECT overdose_deaths
-- 		, year
-- 		, fipscounty::varchar
-- 	FROM overdose_deaths
-- )
-- SELECT overdose_fixed.year
-- 	, SUM(overdose_fixed.overdose_deaths)
-- FROM overdose_fixed
-- 	INNER JOIN fips_county
-- 		USING(fipscounty)
-- WHERE fips_county.state LIKE 'TN'
-- GROUP BY overdose_fixed.year
-- ORDER BY overdose_fixed.year

--Question 4: Is there an association between rates of opioid prescriptions and overdose deaths by county?
-- WITH overdose_fixed AS (			-- Overdose deaths by county, to be merged with other dataframes in Python
-- 	SELECT overdose_deaths
-- 		, year
-- 		, fipscounty::varchar
-- 	FROM overdose_deaths
-- )
-- SELECT fips_county.county
-- 	, fips_county.fipscounty
-- 	, SUM(overdose_fixed.overdose_deaths) AS total_deaths
-- FROM overdose_fixed
-- 	INNER JOIN fips_county
-- 		USING(fipscounty)
-- WHERE fips_county.state ILIKE 'TN'
-- GROUP BY fips_county.county
-- 	, fips_county.fipscounty

-- Question 5: Is there any association between a particular type of opioid and number of overdose deaths?
-- WITH max_zips AS (				-- Grouping opioids by primary active ingredient and county prescribed
-- 	SELECT DISTINCT zip
-- 		, MAX(tot_ratio) as max_ratio
-- 	FROM zip_fips
-- 	GROUP BY zip
-- )
-- , sort_fips AS (	
-- 	SELECT zip_fips.zip
-- 		, zip_fips.fipscounty
-- 		, zip_fips.tot_ratio
-- 	FROM zip_fips
-- 		INNER JOIN max_zips
-- 			ON zip_fips.zip = max_zips.zip
-- 			AND zip_fips.tot_ratio = max_zips.max_ratio
-- )
-- , overdose_fixed AS (
-- 	SELECT overdose_deaths
-- 		, year
-- 		, fipscounty::varchar
-- 	FROM overdose_deaths
-- )
-- , drug_flag AS (
-- 	SELECT drug_name
-- 		, generic_name
-- 		, CASE WHEN generic_name ILIKE '%FENTANYL%' THEN 'FENTANYL'
-- 			WHEN generic_name ILIKE '%HYDROCODONE%' THEN 'HYDROCODONE'
-- 			WHEN generic_name ILIKE '%CODEINE%' THEN 'CODEINE'
-- 			WHEN generic_name ILIKE '%MORPHINE%' THEN 'MORPHINE'
-- 			WHEN generic_name ILIKE '%METHADONE%' THEN 'METHADONE'
-- 			WHEN generic_name ILIKE '%OXYCODONE%' THEN 'OXYCODONE'
-- 			WHEN generic_name ILIKE '%HYDROMORPHONE%' THEN 'HYDROMORPHONE'
-- 			WHEN generic_name ILIKE '%TRAMADOL%' THEN 'TRAMADOL'
-- 			WHEN generic_name ILIKE '%BUPRENORPHINE%' THEN 'BUPRENORPHINE'
-- 			WHEN generic_name ILIKE '%OPIUM%' THEN 'OPIUM'
-- 			WHEN generic_name ILIKE '%BUTORPHANOL%' THEN 'BUTORPHANOL'
-- 			WHEN generic_name ILIKE '%TAPENTADOL%' THEN 'TAPENTADOL'
-- 			WHEN generic_name ILIKE '%OXYMORPHONE%' THEN 'OXYMORPHONE'
-- 			END AS opioid_type
-- 	FROM drug
-- 	WHERE opioid_drug_flag ILIKE 'Y'
-- )
-- SELECT fips_county.county
-- 	,	drug_flag.opioid_type
-- 	,	SUM(prescription.total_claim_count) AS total_prescribed
-- FROM fips_county
-- 	INNER JOIN population
-- 		USING (fipscounty)
-- 	INNER JOIN sort_fips
-- 		USING (fipscounty)
-- 	INNER JOIN prescriber
-- 		ON sort_fips.zip = prescriber.nppes_provider_zip5
-- 	INNER JOIN prescription
-- 		USING (npi)
-- 	INNER JOIN drug
-- 		USING (drug_name)
-- 	INNER JOIN drug_flag
-- 		USING(drug_name , generic_name)
-- WHERE fips_county.state ILIKE 'TN'
-- GROUP BY fips_county.county, drug_flag.opioid_type
-- ORDER BY fips_county.county, total_prescribed DESC


-- WITH max_zips AS (				-- Grouping opioids by generic name and county prescribed
-- 	SELECT DISTINCT zip
-- 		, MAX(tot_ratio) as max_ratio
-- 	FROM zip_fips
-- 	GROUP BY zip
-- )
-- , sort_fips AS (	
-- 	SELECT zip_fips.zip
-- 		, zip_fips.fipscounty
-- 		, zip_fips.tot_ratio
-- 	FROM zip_fips
-- 		INNER JOIN max_zips
-- 			ON zip_fips.zip = max_zips.zip
-- 			AND zip_fips.tot_ratio = max_zips.max_ratio
-- )
-- , overdose_fixed AS (
-- 	SELECT overdose_deaths
-- 		, year
-- 		, fipscounty::varchar
-- 	FROM overdose_deaths
-- )
-- SELECT fips_county.county
-- 	,	drug.drug_name
-- 	, SUM(prescription.total_claim_count) as total_prescribed
-- FROM fips_county
-- 	INNER JOIN population
-- 		USING (fipscounty)
-- 	INNER JOIN sort_fips
-- 		USING (fipscounty)
-- 	INNER JOIN prescriber
-- 		ON sort_fips.zip = prescriber.nppes_provider_zip5
-- 	INNER JOIN prescription
-- 		USING (npi)
-- 	INNER JOIN drug
-- 		USING (drug_name)
-- WHERE fips_county.state ILIKE '%TN%'
-- 	AND drug.opioid_drug_flag ILIKE 'Y'
-- GROUP BY fips_county.county
-- 	, drug.drug_name
-- ORDER BY fips_county.county
-- 	, total_prescribed DESC





